name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Unit tests
        run: pytest -q
      - name: Demo run
        run: |
          mkdir -p data reports
          python scripts/make_synthetic.py --out data/demo.csv
          unreanchor run --data data/demo.csv --config configs/config.sample.yaml --out reports
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
